# **Dashboard: Prepare Data for Dashboard**

## Objectives

* Prepare a single csv file for presenting the data on a Dashboard

## Inputs

* data/processed/01e_df_co2_pop_gdp_degc_1990_2024.csv
* data/processed/01c_df_owid_src_country_2000_2024.csv

## Outputs

* data/processed/04_df_co2_pop_gdp_degc_srcs_1990_2024.csv

---

# Set Up directories and Import Necessary Libraries

In [1]:
# System and OS related tasks
import sys
import os

# Add the project root to Python path
project_root = os.path.abspath('..')
sys.path.insert(0, project_root)

# path to directories
raw_dir = '../data/raw'
processed_dir = '../data/processed'

In [2]:
# Get the necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('whitegrid') # sets a white background with grid lines

# Merging the CO<sub>2</sub>, Population, GDP and Energy Sources Data

📌 Read in the main CO<sub>2</sub>, populations and GDP per capita, PPP (constant 2021 international $) from data/processed/01e_df_co2_pop_gdp_degc_1990_2024.csv. This csv covers data from 1990 to 2024.

In [3]:
data_columns = [
 "country_code_iso3"
    , "country_name_iso3"
    , "year"
    , "co2_pc"
    , "population"
    , "gdp_constant_ppp_pc"
    , "degc"
]
column_dtypes = {
    "country_code_iso3": str
    , "country_name_iso3": str
    , "year": int
    , "co2_pc" : float
    , "population" : float
    , "gdp_constant_ppp_pc": float
    , "degc": float
    }

file_name = "01e_df_co2_pop_gdp_degc_1990_2024.csv"
df_co2_pop_gdp_degc_1990_2024 = pd.read_csv(
 f"{processed_dir}/{file_name}",
    header=0,
    names=data_columns,
    dtype=column_dtypes
    )

In [4]:
df_co2_pop_gdp_degc_1990_2024.head(5)

,country_code_iso3,country_name_iso3,year,co2_pc,population,gdp_constant_ppp_pc,degc
0,AFG,Afghanistan,1990,0.168054,12045664.0,NaN,13.25
1,AFG,Afghanistan,1991,0.156411,12238879.0,NaN,12.70
2,AFG,Afghanistan,1992,0.111609,13278983.0,NaN,12.42
3,AFG,Afghanistan,1993,0.099506,14943175.0,NaN,12.71
4,AFG,Afghanistan,1994,0.089462,16250800.0,NaN,12.95

📌 Read in the energy sources data from data/processed/01c_df_owid_src_country_2000_2024.csv. This csv covers data from 2000 to 2024.

In [6]:
data_columns = [
 "country"
    , "country_code"
    , "year"
    , "other_renewables"
    , "bioenergy"
    , "solar"
    , "wind"
    , "hydropower"
    , "nuclear"
    , "oil"
    , "gas"
    , "coal"
    , "country_code_iso3"
]
column_dtypes = {
 "country": str
    , "country_code": str
    , "year": int
    , "other_renewables": float
    , "bioenergy": float
    , "solar": float
    , "wind": float
    , "hydropower": float
    , "nuclear": float
    , "oil": float
    , "gas": float
    , "coal": float
    , "country_code_iso3": str
}

file_name = "01c_df_owid_src_country_2000_2024.csv"
df_owid_src_country_2000_2024 = pd.read_csv(
 f"{processed_dir}/{file_name}",
    header=0,
    names=data_columns,
    dtype=column_dtypes
    )

In [7]:
df_owid_src_country_2000_2024.head(5)

,country,country_code,year,other_renewables,bioenergy,solar,wind,hydropower,nuclear,oil,gas,coal,country_code_iso3
0,Afghanistan,AFG,2000,0.0,0.0,0.0,0.0,0.31,0.0,0.17,0.0,0.00,AFG
1,Afghanistan,AFG,2001,0.0,0.0,0.0,0.0,0.50,0.0,0.15,0.0,0.04,AFG
2,Afghanistan,AFG,2002,0.0,0.0,0.0,0.0,0.56,0.0,0.11,0.0,0.04,AFG
3,Afghanistan,AFG,2003,0.0,0.0,0.0,0.0,0.63,0.0,0.19,0.0,0.09,AFG
4,Afghanistan,AFG,2004,0.0,0.0,0.0,0.0,0.56,0.0,0.17,0.0,0.06,AFG

📌 Merge the energy sources data keeping all the rows in main CO<sub>2</sub>, populations and GDP per capita, PPP (constant 2021 international $).

In [16]:
df_all_data_1990_2024 = df_co2_pop_gdp_degc_1990_2024.merge(
    df_owid_src_country_2000_2024
    , left_on=["country_code_iso3","year"]
    , right_on=["country_code_iso3","year"]
    , how="left"
)

df_all_data_1990_2024

,country_code_iso3,country_name_iso3,year,co2_pc,population,gdp_constant_ppp_pc,degc,country,country_code,other_renewables,bioenergy,solar,wind,hydropower,nuclear,oil,gas,coal
0,AFG,Afghanistan,1990,0.168054,12045664.0,NaN,13.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,1991,0.156411,12238879.0,NaN,12.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Afghanistan,1992,0.111609,13278983.0,NaN,12.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Afghanistan,1993,0.099506,14943175.0,NaN,12.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Afghanistan,1994,0.089462,16250800.0,NaN,12.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7468,ZWE,Zimbabwe,2020,0.546847,15526887.0,4527.719881,21.94,Zimbabwe,ZWE,0.0,0.10,0.02,0.0,3.81,0.0,0.04,0.0,2.74
7469,ZWE,Zimbabwe,2021,0.647125,15797220.0,4827.088694,21.89,Zimbabwe,ZWE,0.0,0.11,0.02,0.0,5.93,0.0,0.00,0.0,2.51
7470,ZWE,Zimbabwe,2022,0.761205,16069061.0,5036.761361,21.83,Zimbabwe,ZWE,0.0,0.11,0.03,0.0,5.88,0.0,0.00,0.0,2.92
7471,ZWE,Zimbabwe,2023,0.822681,16340829.0,5218.022665,22.09,Zimbabwe,ZWE,0.0,0.12,0.03,0.0,5.46,0.0,0.00,0.0,2.70
7472,ZWE,Zimbabwe,2024,0.823666,16634366.0,5215.253011,22.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
columns_keep = [
    'country_code_iso3'
    , 'country_name_iso3'
    , 'year'
    , 'co2_pc'
    , 'population'
    , 'gdp_constant_ppp_pc'
    , 'degc'
    , 'other_renewables'
    , 'bioenergy'
    , 'solar'
    , 'wind'
    , 'hydropower'
    , 'nuclear'
    , 'oil'
    , 'gas'
    , 'coal'
]

df_all_data_1990_2024 = df_all_data_1990_2024[columns_keep].copy()

df_all_data_1990_2024

,country_code_iso3,country_name_iso3,year,co2_pc,population,gdp_constant_ppp_pc,degc,other_renewables,bioenergy,solar,wind,hydropower,nuclear,oil,gas,coal
0,AFG,Afghanistan,1990,0.168054,12045664.0,NaN,13.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,1991,0.156411,12238879.0,NaN,12.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Afghanistan,1992,0.111609,13278983.0,NaN,12.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Afghanistan,1993,0.099506,14943175.0,NaN,12.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Afghanistan,1994,0.089462,16250800.0,NaN,12.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7468,ZWE,Zimbabwe,2020,0.546847,15526887.0,4527.719881,21.94,0.0,0.10,0.02,0.0,3.81,0.0,0.04,0.0,2.74
7469,ZWE,Zimbabwe,2021,0.647125,15797220.0,4827.088694,21.89,0.0,0.11,0.02,0.0,5.93,0.0,0.00,0.0,2.51
7470,ZWE,Zimbabwe,2022,0.761205,16069061.0,5036.761361,21.83,0.0,0.11,0.03,0.0,5.88,0.0,0.00,0.0,2.92
7471,ZWE,Zimbabwe,2023,0.822681,16340829.0,5218.022665,22.09,0.0,0.12,0.03,0.0,5.46,0.0,0.00,0.0,2.70
7472,ZWE,Zimbabwe,2024,0.823666,16634366.0,5215.253011,22.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

📌 export to csv

In [18]:
df_all_data_1990_2024.to_csv(f'{processed_dir}/04_df_all_data_1990_2024.csv', index=False)
print(f"Exported: {processed_dir}/04_df_all_data_1990_2024.csv")

Exported: ../data/processed/04_df_all_data_1990_2024.csv

---